services:
  grafana:
    user: root
    container_name: 'cognitedata-datasource'

    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-11.0.0}
        development: ${DEVELOPMENT:-false}
    ports:
      - 2999:3000/tcp
    security_opt:
      - 'apparmor:unconfined'
      - 'seccomp:unconfined'
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./dist:/var/lib/grafana/plugins/cognitedata-datasource
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/cognitedata-datasource

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.cognitedata-datasource:debug
      GF_LOG_LEVEL: info
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: cognitedata-datasource
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      COGNITE_HOST: ${COGNITE_HOST}
      COGNITE_PROJECT: ${COGNITE_PROJECT}
      TOKEN_URL: ${TOKEN_URL}
