version: '3.0'

services:
  grafana:
    container_name: 'cognitedata-datasource'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-11.0.0}
    ports:
      - 2999:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/cognitedata-datasource
      - ./provisioning:/etc/grafana/provisioning
