// Jest setup provided by Grafana scaffolding
import './.config/jest-setup';

// Grafana's Select opens its menu behind an IntersectionObserver, which jsdom does
// not implement. Without this, interacting with any dropdown throws instead of
// opening. The scaffolded setup above is regenerated by create-plugin, so
// extensions belong here.
if (!global.IntersectionObserver) {
  global.IntersectionObserver = class {
    observe() {}
    unobserve() {}
    disconnect() {}
    takeRecords() {
      return [];
    }
  };
}

// Used by Grafana's virtualised menus for the same reason.
if (!global.ResizeObserver) {
  global.ResizeObserver = class {
    observe() {}
    unobserve() {}
    disconnect() {}
  };
}
